TrajectoryPlannerROS:
  controller_frequency: 3
  max_vel_x: 0.15
  min_vel_x: 0.05
  max_vel_y: 0.0
  min_vel_y: 0.0
  escape_vel: -0.1
  min_in_place_vel_theta: 0.5
  acc_lim_theta: 0.1
  acc_lim_x: 0.1
  acc_lim_y: 0.1
  holonomic_robot: false
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  path_distance_bias: 0.8
  goal_distance_bias: 0.4
  meter_scoring: true
  recovery_behavior_enabled: true
  clearing_rotation_allowed: true
  
  
