puppy:
   # Position Controllers ---------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_joint1
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_joint1
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rb_joint1
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lb_joint1
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_joint2
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_joint2
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: rb_joint2
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: lb_joint2
    pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
