(cl:defpackage puppy_control-srv
  (:use )
  (:export
   "SETFLOAT64"
   "<SETFLOAT64-REQUEST>"
   "SETFLOAT64-REQUEST"
   "<SETFLOAT64-RESPONSE>"
   "SETFLOAT64-RESPONSE"
   "SETFLOAT64LIST"
   "<SETFLOAT64LIST-REQUEST>"
   "SETFLOAT64LIST-REQUEST"
   "<SETFLOAT64LIST-RESPONSE>"
   "SETFLOAT64LIST-RESPONSE"
   "SETINT64"
   "<SETINT64-REQUEST>"
   "SETINT64-REQUEST"
   "<SETINT64-RESPONSE>"
   "SETINT64-RESPONSE"
   "SETRUNACTIONNAME"
   "<SETRUNACTIONNAME-REQUEST>"
   "SETRUNACTIONNAME-REQUEST"
   "<SETRUNACTIONNAME-RESPONSE>"
   "SETRUNACTIONNAME-RESPONSE"
  ))

