#!/usr/bin/env python3
# encoding: utf-8

language = {
        'label_action':{'Chinese':'动作组：',
                        'English':'Action group: '},
        'Button_DelectSingle':{'Chinese':'单个擦除',
                                'English':'Erase'},
        'Button_AllDelect':{'Chinese':'全部擦除',
                            'English':'Erase all'},
        'Button_RunAction':{'Chinese':'动作组运行',
                            'English':'Run action'},
        'Button_StopAction':{'Chinese':'停止',
                            'English':'Stop'},
        'Button_Quit':{'Chinese':'退出',
                        'English':'Quit'},
        'Button_Refresh':{'Chinese':'刷新',
                        'English':'Refresh'},
        'checkBox':{    'Chinese':'循环',
                        'English':'Loop'},
        'Button_Run':{'Chinese':'运行',
                        'English':'Run'},
        'Button_DownloadDeviation':{'Chinese':'保存偏差',
                                    'English':'Save deviation'},
        'Button_ReSetServos':{'Chinese':'复位舵机',
                            'English':'Reset servos'},
        'Button_ServoPowerDown':{'Chinese':'舵机掉电',
                                'English':'Power Fail'},
        'tableWidget.horizontalHeaderItem(1)':{'Chinese':'编号',
                                                'English':'Index'},
        'tableWidget.horizontalHeaderItem(2)':{'Chinese':'时间',
                                                'English':'Time'},
        'Button_OpenActionGroup':{'Chinese':'打开动作文件',
                                'English':'Open action file'},
        'Button_SaveActionGroup':{'Chinese':'保存动作文件',
                                    'English':'Save action file'},
        'Button_TandemActionGroup':{'Chinese':'串联动作文件',
                                    'English':'Integrate files'},
        'label_time':{'Chinese':'动作时间',
                    'English':'Time'},
        'Button_AddAction':{'Chinese':'添加动作',
                            'English':'Add action'},
        'Button_DelectAction':{'Chinese':'删除动作',
                                'English':'Delete action'},
        'Button_UpdateAction':{'Chinese':'更新动作',
                                'English':'Update action'},
        'Button_InsertAction':{'Chinese':'插入动作',
                                'English':'Insert action'},
        'Button_MoveUpAction':{'Chinese':'上移动作',
                                'English':'Move up'},
        'Button_MoveDownAction':{'Chinese':'下移动作',
                                'English':'Move down'},
        'label_time_2':{'Chinese':'总时长',
                        'English':'Total time'},
        'Button_DelectAllAction':{'Chinese':'删除全部',
                                    'English':'Delete all'},
        # 'Button_AngularReadback':{'Chinese':'角度回读',
        #     'English':''},
        'label_servoL_1':{'Chinese':'<html><head/><body><p align=\"center\">后</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Back</p></body></html>'},
        'label_servoR_1':{'Chinese':'<html><head/><body><p align=\"center\">前</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Front</p></body></html>'},
        'label_servoL_5':{'Chinese':'<html><head/><body><p align=\"center\">后</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Back</p></body></html>'},
        'label_servoR_5':{'Chinese':'<html><head/><body><p align=\"center\">前</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Front</p></body></html>'},
        'label_servoR_6':{'Chinese':'<html><head/><body><p align=\"center\">上</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Up</p></body></html>'},
        'label_servoL_6':{'Chinese':'<html><head/><body><p align=\"center\">下</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Down</p></body></html>'},
        'label_servoL_2':{'Chinese':'<html><head/><body><p align=\"center\">下</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Down</p></body></html>'},
        'label_servoR_2':{'Chinese':'<html><head/><body><p align=\"center\">上</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Up</p></body></html>'},
        'label_servoL_7':{'Chinese':'<html><head/><body><p align=\"center\">前</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Front</p></body></html>'},
        'label_servoR_7':{'Chinese':'<html><head/><body><p align=\"center\">后</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Back</p></body></html>'},
        'label_servoR_3':{'Chinese':'<html><head/><body><p align=\"center\">后</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Back</p></body></html>'},
        'label_servoL_3':{'Chinese':'<html><head/><body><p align=\"center\">前</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Front</p></body></html>'},
        'label_servoR_4':{'Chinese':'<html><head/><body><p align=\"center\">下</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Down</p></body></html>'},
        'label_servoL_4':{'Chinese':'<html><head/><body><p align=\"center\">上</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Up</p></body></html>'},
        'label_servoL_8':{'Chinese':'<html><head/><body><p align=\"center\">上</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Up</p></body></html>'},
        'label_servoR_8':{'Chinese':'<html><head/><body><p align=\"center\">下</p></body></html>',
                            'English':'<html><head/><body><p align=\"center\">Down</p></body></html>'},
        'tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1)':{'Chinese':'普通模式',
                        'English':'Normal mode'},
        'tableWidget_Coord.horizontalHeaderItem(1)':{'Chinese':'编号',
                        'English':'Index'},
        'tableWidget_Coord.horizontalHeaderItem(2)':{'Chinese':'时间',
                        'English':'Time'},
        'checkBox_run_Coord_cycle':{'Chinese':'循环',
                        'English':'Loop'},
        'Button_Run_Coord':{'Chinese':'运行',
                        'English':'Run'},
        'Button_Reset_Coord':{'Chinese':'复位坐标',
                        'English':'Reset'},
        'label_time_4':{'Chinese':'动作时间',
                        'English':'Time'},
        'Button_AddCoord':{'Chinese':'添加动作',
                        'English':'Add action'},
        'Button_DelectCoord':{'Chinese':'删除动作',
                        'English':'Delete action'},
        'Button_UpdateCoord':{'Chinese':'更新动作',
                        'English':'Update action'},
        'Button_MoveUpCoord':{'Chinese':'上移动作',
                        'English':'Move up'},
        'Button_MoveDownCoord':{'Chinese':'下移动作',
                        'English':'Move down'},
        'Button_DelectAllCoord':{'Chinese':'删除全部',
                        'English':'Delete all'},
        'label_time_3':{'Chinese':'总时长',
                        'English':'Total time'},
        'Button_InsertCoord':{'Chinese':'插入动作',
                        'English':'Insert action'},
        'Button_OpenActionGroup_Coord':{'Chinese':'打开动作文件',
                        'English':'Open action file'},
        'Button_SaveActionGroup_Coord':{'Chinese':'保存动作文件',
                        'English':'Save action file'},
        'Button_TandemActionGroup_Coord':{'Chinese':'串联动作文件',
                        'English':'Integrate files'},
        'label_action_2':{'Chinese':'动作组：',
                        'English':'Action group: '},
        'Button_DelectSingle_Coord':{'Chinese':'单个擦除',
                        'English':'Erase'},
        'Button_AllDelect_Coord':{'Chinese':'全部擦除',
                        'English':'Erase all'},
        'Button_RunAction_Coord':{'Chinese':'动作组运行',
                        'English':'Run action'},
        'Button_StopAction_Coord':{'Chinese':'停止',
                        'English':'Stop'},
        'Button_Refresh_Coord':{'Chinese':'刷新',
                        'English':'Refresh'},
        'pushButton_quit2':{'Chinese':'退出',
                        'English':'Quit'},
        'tabWidget.setTabText(self.tabWidget.indexOf(self.tab)':{'Chinese':'坐标模式',
                        'English':'Coordinate mode'},
        



        'MessageBox':{
            'tabchange':{'Chinese':'使用此面板时，请确保只连接了一个舵机，否则会引起冲突！',
                            'English':'Before debugging servo,make sure that the servo controller is connected with ONE servo.Otherwise it may cause a conflict!'},
            'action_one':{'Chinese':'运行出错!',
                            'English':'Running error'},
            'action_one_coord':{'Chinese':'运行出错!',
                            'English':'Running error'},
            'Button_AddCoord':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'Button_UpdateCoord':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'Button_InsertCoord':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'servoPowerDown':{'Chinese':'掉电成功',
                            'English':'success'},
            'addAction':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'updateAction':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'insertAction':{'Chinese':'运行时间必须大于5',
                            'English':'Run time must greater than 5'},
            'button_run_coord':{'Chinese':'请先添加动作!',
                            'English':'Add action first!'},
            'Button_Run_Coord_Run':{'Chinese':'停止',
                            'English':'Stop'},
            'Button_Run_Coord_Stop':{'Chinese':'运行结束!',
                            'English':'Run over!'},
            'operate2_coord':{'Chinese':'运行结束!',
                            'English':'Run over!'},
            'button_run':{'Chinese':'请先添加动作!',
                            'English':'Add action first!'},
            'operate2':{'Chinese':'运行结束!',
                            'English':'Run over!'},
            'Button_Run_Stop':{'Chinese':'运行结束!',
                            'English':'Run over!'},
            'action_online':{'Chinese':'运行出错!',
                            'English':'Run error!'},
            'button_flie_operate':{'Chinese':'动作组错误',
                            'English':'Wrong action format'},
            'saveActionGroup':{'Chinese':'动作列表是空的哦，没啥要保存的',
                            'English':'The action list is empty，nothing to save'},
            'Button_SaveActionGroup_Coord':{'Chinese':'动作列表是空的哦，没啥要保存的',
                            'English':'The action list is empty，nothing to save'},
            'downloadDeviation':{'Chinese':'保存偏差成功!',
                            'English':'success!'},
            'tandemActionGroup':{'Chinese':'动作组错误',
                            'English':'Wrong action format'},
            'Button_TandemActionGroup_Coord':{'Chinese':'动作组错误',
                            'English':'Wrong action format'},
            'allDelect':{'Chinese':'此操作会删除所有动作组，是否继续？',
                            'English':''},
            'Button_AllDelect_Coord':{'Chinese':'此操作会删除所有动作组，是否继续？',
                            'English':''},
            'Button_DelectAllCoord':{'Chinese':'此操作会删除列表中的所有动作，是否继续？',
                            'English':''},
            'delectAllAction':{'Chinese':'此操作会删除列表中的所有动作，是否继续？',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
            '':{'Chinese':'',
                            'English':''},
                
        },
        
        
    }