// Generated by gencpp from file puppy_control/SetFloat64.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETFLOAT64_H
#define PUPPY_CONTROL_MESSAGE_SETFLOAT64_H

#include <ros/service_traits.h>


#include <puppy_control/SetFloat64Request.h>
#include <puppy_control/SetFloat64Response.h>


namespace puppy_control
{

struct SetFloat64
{

typedef SetFloat64Request Request;
typedef SetFloat64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64
} // namespace puppy_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::puppy_control::SetFloat64 > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::puppy_control::SetFloat64&) { return value(); }
};

template<>
struct DataType< ::puppy_control::SetFloat64 > {
  static const char* value()
  {
    return "puppy_control/SetFloat64";
  }

  static const char* value(const ::puppy_control::SetFloat64&) { return value(); }
};


// service_traits::MD5Sum< ::puppy_control::SetFloat64Request> should match
// service_traits::MD5Sum< ::puppy_control::SetFloat64 >
template<>
struct MD5Sum< ::puppy_control::SetFloat64Request>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetFloat64 >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetFloat64Request> should match
// service_traits::DataType< ::puppy_control::SetFloat64 >
template<>
struct DataType< ::puppy_control::SetFloat64Request>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetFloat64 >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::puppy_control::SetFloat64Response> should match
// service_traits::MD5Sum< ::puppy_control::SetFloat64 >
template<>
struct MD5Sum< ::puppy_control::SetFloat64Response>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetFloat64 >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetFloat64Response> should match
// service_traits::DataType< ::puppy_control::SetFloat64 >
template<>
struct DataType< ::puppy_control::SetFloat64Response>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetFloat64 >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETFLOAT64_H
