// Generated by gencpp from file puppy_control/SetFloat64List.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETFLOAT64LIST_H
#define PUPPY_CONTROL_MESSAGE_SETFLOAT64LIST_H

#include <ros/service_traits.h>


#include <puppy_control/SetFloat64ListRequest.h>
#include <puppy_control/SetFloat64ListResponse.h>


namespace puppy_control
{

struct SetFloat64List
{

typedef SetFloat64ListRequest Request;
typedef SetFloat64ListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64List
} // namespace puppy_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::puppy_control::SetFloat64List > {
  static const char* value()
  {
    return "5739026f6f0517440e663ba60441de94";
  }

  static const char* value(const ::puppy_control::SetFloat64List&) { return value(); }
};

template<>
struct DataType< ::puppy_control::SetFloat64List > {
  static const char* value()
  {
    return "puppy_control/SetFloat64List";
  }

  static const char* value(const ::puppy_control::SetFloat64List&) { return value(); }
};


// service_traits::MD5Sum< ::puppy_control::SetFloat64ListRequest> should match
// service_traits::MD5Sum< ::puppy_control::SetFloat64List >
template<>
struct MD5Sum< ::puppy_control::SetFloat64ListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetFloat64List >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64ListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetFloat64ListRequest> should match
// service_traits::DataType< ::puppy_control::SetFloat64List >
template<>
struct DataType< ::puppy_control::SetFloat64ListRequest>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetFloat64List >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64ListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::puppy_control::SetFloat64ListResponse> should match
// service_traits::MD5Sum< ::puppy_control::SetFloat64List >
template<>
struct MD5Sum< ::puppy_control::SetFloat64ListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetFloat64List >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64ListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetFloat64ListResponse> should match
// service_traits::DataType< ::puppy_control::SetFloat64List >
template<>
struct DataType< ::puppy_control::SetFloat64ListResponse>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetFloat64List >::value();
  }
  static const char* value(const ::puppy_control::SetFloat64ListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETFLOAT64LIST_H
