// Generated by gencpp from file puppy_control/SetFloat64ListRequest.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETFLOAT64LISTREQUEST_H
#define PUPPY_CONTROL_MESSAGE_SETFLOAT64LISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puppy_control
{
template <class ContainerAllocator>
struct SetFloat64ListRequest_
{
  typedef SetFloat64ListRequest_<ContainerAllocator> Type;

  SetFloat64ListRequest_()
    : data()  {
    }
  SetFloat64ListRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloat64ListRequest_

typedef ::puppy_control::SetFloat64ListRequest_<std::allocator<void> > SetFloat64ListRequest;

typedef boost::shared_ptr< ::puppy_control::SetFloat64ListRequest > SetFloat64ListRequestPtr;
typedef boost::shared_ptr< ::puppy_control::SetFloat64ListRequest const> SetFloat64ListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator1> & lhs, const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator1> & lhs, const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puppy_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puppy_control/SetFloat64ListRequest";
  }

  static const char* value(const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n"
;
  }

  static const char* value(const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloat64ListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puppy_control::SetFloat64ListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puppy_control::SetFloat64ListRequest_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETFLOAT64LISTREQUEST_H
