// Generated by gencpp from file puppy_control/SetInt64.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETINT64_H
#define PUPPY_CONTROL_MESSAGE_SETINT64_H

#include <ros/service_traits.h>


#include <puppy_control/SetInt64Request.h>
#include <puppy_control/SetInt64Response.h>


namespace puppy_control
{

struct SetInt64
{

typedef SetInt64Request Request;
typedef SetInt64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt64
} // namespace puppy_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::puppy_control::SetInt64 > {
  static const char* value()
  {
    return "b8a3204d8bafe68f75673256846654f5";
  }

  static const char* value(const ::puppy_control::SetInt64&) { return value(); }
};

template<>
struct DataType< ::puppy_control::SetInt64 > {
  static const char* value()
  {
    return "puppy_control/SetInt64";
  }

  static const char* value(const ::puppy_control::SetInt64&) { return value(); }
};


// service_traits::MD5Sum< ::puppy_control::SetInt64Request> should match
// service_traits::MD5Sum< ::puppy_control::SetInt64 >
template<>
struct MD5Sum< ::puppy_control::SetInt64Request>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetInt64 >::value();
  }
  static const char* value(const ::puppy_control::SetInt64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetInt64Request> should match
// service_traits::DataType< ::puppy_control::SetInt64 >
template<>
struct DataType< ::puppy_control::SetInt64Request>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetInt64 >::value();
  }
  static const char* value(const ::puppy_control::SetInt64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::puppy_control::SetInt64Response> should match
// service_traits::MD5Sum< ::puppy_control::SetInt64 >
template<>
struct MD5Sum< ::puppy_control::SetInt64Response>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetInt64 >::value();
  }
  static const char* value(const ::puppy_control::SetInt64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetInt64Response> should match
// service_traits::DataType< ::puppy_control::SetInt64 >
template<>
struct DataType< ::puppy_control::SetInt64Response>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetInt64 >::value();
  }
  static const char* value(const ::puppy_control::SetInt64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETINT64_H
